// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teodora-lazarevic/Poll-App/ent/poll"
	"github.com/teodora-lazarevic/Poll-App/ent/polloption"
	"github.com/teodora-lazarevic/Poll-App/ent/predicate"
	"github.com/teodora-lazarevic/Poll-App/ent/vote"
)

// PollOptionQuery is the builder for querying PollOption entities.
type PollOptionQuery struct {
	config
	ctx        *QueryContext
	order      []polloption.OrderOption
	inters     []Interceptor
	predicates []predicate.PollOption
	withPoll   *PollQuery
	withVotes  *VoteQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PollOptionQuery builder.
func (_q *PollOptionQuery) Where(ps ...predicate.PollOption) *PollOptionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PollOptionQuery) Limit(limit int) *PollOptionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PollOptionQuery) Offset(offset int) *PollOptionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PollOptionQuery) Unique(unique bool) *PollOptionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PollOptionQuery) Order(o ...polloption.OrderOption) *PollOptionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPoll chains the current query on the "poll" edge.
func (_q *PollOptionQuery) QueryPoll() *PollQuery {
	query := (&PollClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(polloption.Table, polloption.FieldID, selector),
			sqlgraph.To(poll.Table, poll.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, polloption.PollTable, polloption.PollColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVotes chains the current query on the "votes" edge.
func (_q *PollOptionQuery) QueryVotes() *VoteQuery {
	query := (&VoteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(polloption.Table, polloption.FieldID, selector),
			sqlgraph.To(vote.Table, vote.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, polloption.VotesTable, polloption.VotesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PollOption entity from the query.
// Returns a *NotFoundError when no PollOption was found.
func (_q *PollOptionQuery) First(ctx context.Context) (*PollOption, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{polloption.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PollOptionQuery) FirstX(ctx context.Context) *PollOption {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PollOption ID from the query.
// Returns a *NotFoundError when no PollOption ID was found.
func (_q *PollOptionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{polloption.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PollOptionQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PollOption entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PollOption entity is found.
// Returns a *NotFoundError when no PollOption entities are found.
func (_q *PollOptionQuery) Only(ctx context.Context) (*PollOption, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{polloption.Label}
	default:
		return nil, &NotSingularError{polloption.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PollOptionQuery) OnlyX(ctx context.Context) *PollOption {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PollOption ID in the query.
// Returns a *NotSingularError when more than one PollOption ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PollOptionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{polloption.Label}
	default:
		err = &NotSingularError{polloption.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PollOptionQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PollOptions.
func (_q *PollOptionQuery) All(ctx context.Context) ([]*PollOption, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PollOption, *PollOptionQuery]()
	return withInterceptors[[]*PollOption](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PollOptionQuery) AllX(ctx context.Context) []*PollOption {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PollOption IDs.
func (_q *PollOptionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(polloption.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PollOptionQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PollOptionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PollOptionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PollOptionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PollOptionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PollOptionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PollOptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PollOptionQuery) Clone() *PollOptionQuery {
	if _q == nil {
		return nil
	}
	return &PollOptionQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]polloption.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.PollOption{}, _q.predicates...),
		withPoll:   _q.withPoll.Clone(),
		withVotes:  _q.withVotes.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPoll tells the query-builder to eager-load the nodes that are connected to
// the "poll" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PollOptionQuery) WithPoll(opts ...func(*PollQuery)) *PollOptionQuery {
	query := (&PollClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPoll = query
	return _q
}

// WithVotes tells the query-builder to eager-load the nodes that are connected to
// the "votes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PollOptionQuery) WithVotes(opts ...func(*VoteQuery)) *PollOptionQuery {
	query := (&VoteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVotes = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PollOption.Query().
//		GroupBy(polloption.FieldText).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PollOptionQuery) GroupBy(field string, fields ...string) *PollOptionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PollOptionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = polloption.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//	}
//
//	client.PollOption.Query().
//		Select(polloption.FieldText).
//		Scan(ctx, &v)
func (_q *PollOptionQuery) Select(fields ...string) *PollOptionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PollOptionSelect{PollOptionQuery: _q}
	sbuild.label = polloption.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PollOptionSelect configured with the given aggregations.
func (_q *PollOptionQuery) Aggregate(fns ...AggregateFunc) *PollOptionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PollOptionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !polloption.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PollOptionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PollOption, error) {
	var (
		nodes       = []*PollOption{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPoll != nil,
			_q.withVotes != nil,
		}
	)
	if _q.withPoll != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, polloption.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PollOption).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PollOption{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPoll; query != nil {
		if err := _q.loadPoll(ctx, query, nodes, nil,
			func(n *PollOption, e *Poll) { n.Edges.Poll = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVotes; query != nil {
		if err := _q.loadVotes(ctx, query, nodes,
			func(n *PollOption) { n.Edges.Votes = []*Vote{} },
			func(n *PollOption, e *Vote) { n.Edges.Votes = append(n.Edges.Votes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PollOptionQuery) loadPoll(ctx context.Context, query *PollQuery, nodes []*PollOption, init func(*PollOption), assign func(*PollOption, *Poll)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PollOption)
	for i := range nodes {
		if nodes[i].poll_options == nil {
			continue
		}
		fk := *nodes[i].poll_options
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(poll.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "poll_options" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PollOptionQuery) loadVotes(ctx context.Context, query *VoteQuery, nodes []*PollOption, init func(*PollOption), assign func(*PollOption, *Vote)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PollOption)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(polloption.VotesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.poll_option_votes
		if fk == nil {
			return fmt.Errorf(`foreign-key "poll_option_votes" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "poll_option_votes" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PollOptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PollOptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(polloption.Table, polloption.Columns, sqlgraph.NewFieldSpec(polloption.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, polloption.FieldID)
		for i := range fields {
			if fields[i] != polloption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PollOptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(polloption.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = polloption.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PollOptionGroupBy is the group-by builder for PollOption entities.
type PollOptionGroupBy struct {
	selector
	build *PollOptionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PollOptionGroupBy) Aggregate(fns ...AggregateFunc) *PollOptionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PollOptionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PollOptionQuery, *PollOptionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PollOptionGroupBy) sqlScan(ctx context.Context, root *PollOptionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PollOptionSelect is the builder for selecting fields of PollOption entities.
type PollOptionSelect struct {
	*PollOptionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PollOptionSelect) Aggregate(fns ...AggregateFunc) *PollOptionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PollOptionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PollOptionQuery, *PollOptionSelect](ctx, _s.PollOptionQuery, _s, _s.inters, v)
}

func (_s *PollOptionSelect) sqlScan(ctx context.Context, root *PollOptionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
