// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teodora-lazarevic/Poll-App/ent/poll"
	"github.com/teodora-lazarevic/Poll-App/ent/polloption"
	"github.com/teodora-lazarevic/Poll-App/ent/predicate"
	"github.com/teodora-lazarevic/Poll-App/ent/user"
	"github.com/teodora-lazarevic/Poll-App/ent/vote"
)

// VoteQuery is the builder for querying Vote entities.
type VoteQuery struct {
	config
	ctx        *QueryContext
	order      []vote.OrderOption
	inters     []Interceptor
	predicates []predicate.Vote
	withUser   *UserQuery
	withOption *PollOptionQuery
	withPoll   *PollQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VoteQuery builder.
func (_q *VoteQuery) Where(ps ...predicate.Vote) *VoteQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VoteQuery) Limit(limit int) *VoteQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VoteQuery) Offset(offset int) *VoteQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VoteQuery) Unique(unique bool) *VoteQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VoteQuery) Order(o ...vote.OrderOption) *VoteQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *VoteQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vote.Table, vote.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, vote.UserTable, vote.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOption chains the current query on the "option" edge.
func (_q *VoteQuery) QueryOption() *PollOptionQuery {
	query := (&PollOptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vote.Table, vote.FieldID, selector),
			sqlgraph.To(polloption.Table, polloption.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, vote.OptionTable, vote.OptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPoll chains the current query on the "poll" edge.
func (_q *VoteQuery) QueryPoll() *PollQuery {
	query := (&PollClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vote.Table, vote.FieldID, selector),
			sqlgraph.To(poll.Table, poll.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, vote.PollTable, vote.PollColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Vote entity from the query.
// Returns a *NotFoundError when no Vote was found.
func (_q *VoteQuery) First(ctx context.Context) (*Vote, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{vote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VoteQuery) FirstX(ctx context.Context) *Vote {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Vote ID from the query.
// Returns a *NotFoundError when no Vote ID was found.
func (_q *VoteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{vote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VoteQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Vote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Vote entity is found.
// Returns a *NotFoundError when no Vote entities are found.
func (_q *VoteQuery) Only(ctx context.Context) (*Vote, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{vote.Label}
	default:
		return nil, &NotSingularError{vote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VoteQuery) OnlyX(ctx context.Context) *Vote {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Vote ID in the query.
// Returns a *NotSingularError when more than one Vote ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VoteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{vote.Label}
	default:
		err = &NotSingularError{vote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VoteQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Votes.
func (_q *VoteQuery) All(ctx context.Context) ([]*Vote, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Vote, *VoteQuery]()
	return withInterceptors[[]*Vote](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VoteQuery) AllX(ctx context.Context) []*Vote {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Vote IDs.
func (_q *VoteQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(vote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VoteQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VoteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VoteQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VoteQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VoteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VoteQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VoteQuery) Clone() *VoteQuery {
	if _q == nil {
		return nil
	}
	return &VoteQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]vote.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Vote{}, _q.predicates...),
		withUser:   _q.withUser.Clone(),
		withOption: _q.withOption.Clone(),
		withPoll:   _q.withPoll.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VoteQuery) WithUser(opts ...func(*UserQuery)) *VoteQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithOption tells the query-builder to eager-load the nodes that are connected to
// the "option" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VoteQuery) WithOption(opts ...func(*PollOptionQuery)) *VoteQuery {
	query := (&PollOptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOption = query
	return _q
}

// WithPoll tells the query-builder to eager-load the nodes that are connected to
// the "poll" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VoteQuery) WithPoll(opts ...func(*PollQuery)) *VoteQuery {
	query := (&PollClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPoll = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (_q *VoteQuery) GroupBy(field string, fields ...string) *VoteGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VoteGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = vote.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (_q *VoteQuery) Select(fields ...string) *VoteSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VoteSelect{VoteQuery: _q}
	sbuild.label = vote.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VoteSelect configured with the given aggregations.
func (_q *VoteQuery) Aggregate(fns ...AggregateFunc) *VoteSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VoteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !vote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VoteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Vote, error) {
	var (
		nodes       = []*Vote{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUser != nil,
			_q.withOption != nil,
			_q.withPoll != nil,
		}
	)
	if _q.withUser != nil || _q.withOption != nil || _q.withPoll != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, vote.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Vote).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Vote{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *Vote, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOption; query != nil {
		if err := _q.loadOption(ctx, query, nodes, nil,
			func(n *Vote, e *PollOption) { n.Edges.Option = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPoll; query != nil {
		if err := _q.loadPoll(ctx, query, nodes, nil,
			func(n *Vote, e *Poll) { n.Edges.Poll = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VoteQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Vote, init func(*Vote), assign func(*Vote, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Vote)
	for i := range nodes {
		if nodes[i].user_votes == nil {
			continue
		}
		fk := *nodes[i].user_votes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_votes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *VoteQuery) loadOption(ctx context.Context, query *PollOptionQuery, nodes []*Vote, init func(*Vote), assign func(*Vote, *PollOption)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Vote)
	for i := range nodes {
		if nodes[i].poll_option_votes == nil {
			continue
		}
		fk := *nodes[i].poll_option_votes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(polloption.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "poll_option_votes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *VoteQuery) loadPoll(ctx context.Context, query *PollQuery, nodes []*Vote, init func(*Vote), assign func(*Vote, *Poll)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Vote)
	for i := range nodes {
		if nodes[i].poll_votes == nil {
			continue
		}
		fk := *nodes[i].poll_votes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(poll.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "poll_votes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *VoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(vote.Table, vote.Columns, sqlgraph.NewFieldSpec(vote.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vote.FieldID)
		for i := range fields {
			if fields[i] != vote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(vote.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = vote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VoteGroupBy is the group-by builder for Vote entities.
type VoteGroupBy struct {
	selector
	build *VoteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VoteGroupBy) Aggregate(fns ...AggregateFunc) *VoteGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VoteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoteQuery, *VoteGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VoteGroupBy) sqlScan(ctx context.Context, root *VoteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VoteSelect is the builder for selecting fields of Vote entities.
type VoteSelect struct {
	*VoteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VoteSelect) Aggregate(fns ...AggregateFunc) *VoteSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VoteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoteQuery, *VoteSelect](ctx, _s.VoteQuery, _s, _s.inters, v)
}

func (_s *VoteSelect) sqlScan(ctx context.Context, root *VoteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
